sudo: required

services:
  - docker


before_install:
  - docker build -t eli_if/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eli_if/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-703353052762"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

